# Dockerfile.dev
FROM mcr.microsoft.com/dotnet/sdk:9.0

WORKDIR /app

# Copy everything for development
COPY . ./

# Install SDK dependencies (already included)
# Expose 80 port for dev
EXPOSE 80

# Run using dotnet watch (for local hot reload)
CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:80"]